### ISSUE TITLE
Full score when model is not found

### ISSUE THREAD

**Issue by dennisboerger** [PicnicSupermarket/dbt-score#43]
When scoring a non existing model, the result is a gold medal 🥇 (full score).

```
poetry run python -m dbt_score lint -s unknown_model

2024-06-11 09:10:23,531 WARNING [dbt_score.models] No model found.
Project score: 10.0 🥇
```

I suggest to skip scoring when the model does not exist.

**Comment by matthieucan** [comment]
Well spotted, thanks! Indeed, while the score is "valid" (no model is failing any rule, hence `10`), it doesn't make much sense. PR welcome to skip this output when no model is found :)

**Comment by farmanp** [comment]
I have a PR, #64, that adds a null check to ignore the score if it's null. However, I'm coming across some issues with testing locally on the package itself that I could use some help with.

**Comment by jochemvandooren** [comment]
Hi @farmanp, thanks for opening the PR! :rocket: 

Concerning the test, I suspect you have a `manifest.json` in the default manifest path of your project and you are running the test from there? Not sure, but seems likely. I would have a look at `get_default_manifest_path` in `dbt_utils.py`, let me know!

```python
        # Use default manifest path
        with patch("dbt_score.cli.Config._load_toml_file"):
            result = runner.invoke(lint, catch_exceptions=False)
```

**Comment by farmanp** [comment]
> Hi @farmanp, thanks for opening the PR! 🚀
> 
> Concerning the test, I suspect you have a `manifest.json` in the default manifest path of your project and you are running the test from there? Not sure, but seems likely. I would have a look at `get_default_manifest_path` in `dbt_utils.py`, let me know!
> 
> ```python
>         # Use default manifest path
>         with patch("dbt_score.cli.Config._load_toml_file"):
>             result = runner.invoke(lint, catch_exceptions=False)
> ```

@jochemvandooren I look into this again and tried to run this again. 

```
 pwd                 
/Users/farman/dbt-score
```

I followed the [Contributor's guide](https://dbt-score.picnic.tech/contributing/) and the problem starts here: 

```
pdm run ruff check .
pdm run ruff check --fix
pdm run mypy .
pdm run tox -e lint
```

Here is the tail end of my error logs:

```
dbt-score/bin/daff.py:11284: error: Function is missing a return type annotation  [no-untyped-def]
dbt-score/bin/daff.py:11284: note: Use "-> None" if function does not return a value
dbt-score/bin/daff.py:11285: error: Call to untyped function "main" of "Coopy" in typed context  [no-untyped-call]
Found 2693 errors in 2 files (checked 38 source files)
lint: exit 1 (3.02 seconds) /Users/farman/dbt-score> mypy . pid=35510
.pkg: _exit> python /Users/farman/dbt-score/dbt-score/lib/python3.11/site-packages/pyproject_api/_backend.py True pdm.backend
  lint: FAIL code 1 (5.57=setup[2.51]+cmd[0.04,3.02] seconds)
  evaluation failed :( (5.63 seconds)
```

I even checkout out of my feature branch and tried in `master`. I'm still getting the issue above. Maybe I should open a new issue to track this, unless there's a simpler solution I'm missing?

**Comment by druzhinin-kirill** [comment]
Hey @farmanp !
Could you please share the project tree/structure? 
It looks like you have a `bin` (`dbt-score/bin/daff.py`) folder within the project that should not be part of it (and should not be linted so)

**Comment by matthieucan** [comment]
Indeed, perhaps there's a virtual environment called `dbt-score`, hence the path `dbt-score/dbt-score/bin/`? 🤔 
`pdm` should not create this, at least I've never seen this behavior.

**Comment by dennisboerger** [comment]
Thanks @farmanp for picking this up! Amazing 🚀
