### ISSUE TITLE
Enable/disable rules per schema

### ISSUE THREAD

**Issue by diorge** [PicnicSupermarket/dbt-score#48]
Looking through the documentation, it seems dbt-score only allows rules to be enabled or disabled for the entire project. Would it be feasible to allow enabling/disabling of rules per folder or schema of the project? Example use case: we only enforce our silver-layer (medallion architecture) models to have an engineer as owner.

**Comment by diorge** [comment]
@matthieucan Yeah that makes sense. Correct me if I'm wrong, but that also means we can specialize the generic rules in Python as well, instead of adding config to the TOML file?

```python
from dbt_score import Model, rule, RuleViolation
from dbt_score.rules.generic import has_description

@rule
def some_schema_has_description(model: Model): RuleViolation | None:
    if model.schema == 'some':
        return has_description(model)
```

**Comment by matthieucan** [comment]
Yes, that's true! But for the rules provided in dbt-score (as opposed to your own rules), things should ideally apply to all (most) users.
Hence why having this configurable would be perfect, as folders/schemas are different everywhere. Hope that makes sense!

**Comment by diorge** [comment]
I've been playing around with this. As much as it "works", it can skew the total score of the system by having too many passes. If a certain lint rule should only be applied to a certain models (even the generic `public_model_has_example`), you get to have a higher score by simply having non-matching models.

I'm starting to think the most elegant(?) solution is having rules return not `RuleViolation | None` but rather `RuleViolation | Bool` (or maybe `RuleViolation | SkipRule | None` to be expansible and retrocompatible).

**Comment by matthieucan** [comment]
> I've been playing around with this. As much as it "works", it can skew the total score of the system by having too many passes. If a certain lint rule should only be applied to a certain models (even the generic public_model_has_example), you get to have a higher score by simply having non-matching models.

That's a good point. However, if a rule only applies to a subset of models, I don't think it's a stretch to consider other models compliant with that rule: they are not supposed to abide by a rule, so they are not violating it.

I understand it skews the results in a way, but it also keeps things simpler to understand.

Given the thresholds and rule severity can be easily configured, do you think it's an issue for you? Maybe you have some example to help me understand your use case?

**Comment by diorge** [comment]
Simple example: our project has no SQL examples in any model, but none of the models are marked as public either. If I disable the generic `public_model_has_example` the project gets 6.7 total score, and by enabling it I get 7.8. One of my schemas has 20 models. If I create a rule for SQL examples for these models, using high severity, the project score goes from 6.7 to 7.6.

Logically, I made the linter stricter. But the score shows the project is now in a better place. This inconsistency leads to the metric not being useful. The only way I could implement it in the project, is if we always aim for 100% lint, and any value below it is a meaningless number. By having skips, this inconsistency could perhaps be avoided.

Of course, this maps back to the config of generic rules:
```toml
[tool.dbt-score.rules."some_rule"]
skip_if = "model.schema.lower() == 'public'" # or "model.schema != 'public'" to make it strict to a certain schema
```

Just to add context, our project has 763 models and 17 schemas (each having between 4 and 140 models). The models in each schema are very heterogeneous, worked on by different teams and tailored for different customers and use-cases. While most of the models should have similar rules (descriptions, column descriptions), there are a lot of rules that apply only to a certain schema. If we add ~30 custom rules, say 3 per schema, the score will always be in the 9.5+ level and be pretty meaningless. (We always had these rules, but never enforced it outside of code reviews, so that's why I'm so interested in your tool!)

**Comment by matthieucan** [comment]
Thanks for sharing, that makes a lot of sense! I agree with your reasoning.

I would be in favor of implementing the `skip_if` functionality, unless someones comes with a better proposal.
@jochemvandooren what do you think?

**Comment by jochemvandooren** [comment]
Very interesting proposal! @matthieucan and I had a broader discussion on disabling rules/models and we think this is a very good way forward! :+1: Would you be willing to work on this feature? Of course we are very happy to brainstorm and discuss the feature beforehand, for example providing early feedback on a draft.

**Comment by farmanp** [comment]
Is this actively being worked on or does it still need someone?

**Comment by diorge** [comment]
> Is this actively being worked on or does it still need someone?

I intend to work on a draft the following days.

**Comment by jochemvandooren** [comment]
Fixed by https://github.com/PicnicSupermarket/dbt-score/pull/66!
