### ISSUE TITLE
Support for Python 3.10?

### ISSUE THREAD

**Issue by stlee-aurora** [PicnicSupermarket/dbt-score#50]
Hi team! I love the idea behind `dbt-score`, as I manage a `dbt` project that is steadily growing in size and complexity (and steadily degrading in quality of documentation!).

Unfortunately, my team is constrained to use Python 3.10 - I'm wondering how viable an extension to support 3.10 would be?

Thanks for your time!

**Comment by jochemvandooren** [comment]
Hi, thanks for opening an issue!

It's unfortunate that you are constrained to Python 3.10, however I can imagine you are not the only one. Therefore it probably makes sense to have 3.10 support as well. :+1:

**Comment by stlee-aurora** [comment]
Thanks! I'm happy to look into opening a PR - any particular tips up front on why Python 3.11 was selected as the starting point?

**Comment by jochemvandooren** [comment]
It looks like someone beat you to it! https://github.com/PicnicSupermarket/dbt-score/pull/54

Anyway, for context: https://github.com/PicnicSupermarket/dbt-score/pull/16#discussion_r1587586694
