### ISSUE TITLE
Bug: Silver medal with 10.0 project score

### ISSUE THREAD

**Issue by japborst** [PicnicSupermarket/dbt-score#61]
It appears one can get a `10.0` _project_ score, but still a silver medal
![image](https://github.com/PicnicSupermarket/dbt-score/assets/1426824/2d9a4b28-4db3-4acc-841a-b5cc66204288)

My suspicion is that the score is actually rounded (e.g. 9.95).

**Comment by ohksith** [comment]
![replicatefail](https://github.com/PicnicSupermarket/dbt-score/assets/79146902/d727efa7-43ef-4c5d-8114-73939a09a945)
Unable to replicate

**Comment by ohksith** [comment]
Unable to replicate.
![replicatefail](https://github.com/PicnicSupermarket/dbt-score/assets/79146902/995d3989-12f1-4695-9644-31f90141cae5)

**Comment by ohksith** [comment]
Unable to replicate 
![fail_replicate](https://github.com/PicnicSupermarket/dbt-score/assets/79146902/0dc52786-ad7b-44df-9f7f-c74607f84afd)

**Comment by japborst** [comment]
Let me add more info: in this case there are multiple models being scored. One of them has a rule violation (medium), which results in a 8.9 score for that model. All other (22x) models have a score of 10.0

The following math is applied:
```
(22*10.0+8.9)/23 = 9.95
```

Which is then a 10.0 when you round.

**Comment by farmanp** [comment]
@japborst - could you provide steps to reproduce this issue?
