### ISSUE TITLE
Feature Request - Add a developer setup guide 

### ISSUE THREAD

**Issue by farmanp** [PicnicSupermarket/dbt-score#65]
I am requesting to add a developer setup guide for allowing users to contribute to this project!

**Is your feature request related to a problem? Please describe.**  
I've noticed that the current contributor guide for dbt-score does not have detailed information on setting up and using the development environment with PDM. This makes it challenging for new contributors to set up their environment and start contributing.

**Describe the solution you'd like**  
A developer guide included in the dbt-score documentation. This guide would include:
- Step-by-step instructions for setting up the development environment using PDM.
- Detailed explanations of the scripts and commands used in the project, such as linting, testing, and building the docs.
- A clear description of the build system setup from the `pyproject.toml` file.
- Guidance on best practices when contributing to the project, including how to propose new features or rules.

To support this, I am willing to help draft this guide based on my own experiences setting up the environment and contribute by sharing code snippets and command examples that have worked for me

**Describe alternatives you've considered**  
As an alternative to a full developer guide, a series of blog posts or wiki pages that cover various aspects of the development process could be considered. These could be linked directly from the README to assist new contributors. Additionally, enhancing the comments within the `pyproject.toml` could partially address the need for more detailed setup instructions.

**Comment by jochemvandooren** [comment]
Hi @farmanp, thanks for your elaborate issue! I think most of the things you listed is actually covered here: https://dbt-score.picnic.tech/contributing/. Could you check it out, if it covers all your questions?

The link to the contributors guide can be found in the [README](https://github.com/PicnicSupermarket/dbt-score/blob/master/README.md#contributing), maybe it's a little bit hard to find?

**Comment by WobblyRobbly** [comment]
PDM was new to me and I followed the guide and this allowed me to do my first PR on this project  😃

**Comment by farmanp** [comment]
Good points everybody! I'm going to close this issue and familiarize myself with the DBT package first. Thanks for the inputs here.
